((docker nil)
 (docker-compose nil)
 (docker-compose-up nil)
 (docker-container-ls
  ("--all" "--filter Status=Up")
  ("--all" "--filter Running")
  ("--last 100" "--all")
  nil)
 (docker-container-rm nil)
 (docker-container-stop nil)
 (docker-image-ls
  ("--filterRunning"))
 (docker-volume-rm nil)
 (magit-commit nil)
 (magit-diff
  ("--no-ext-diff" "--stat"))
 (magit-dispatch nil)
 (magit-gitignore nil)
 (magit-pull nil)
 (magit-push nil)
 (transient:docker-container-ls:--filter\  "Status=Up" "Running")
 (transient:docker-container-ls:--last\  "100")
 (transient:docker-image-ls:--filter "Running"))
